// <auto-generated />
namespace VehicleRentalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class booking_table_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(booking_table_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "202310170648236_booking_table_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
