// <auto-generated />
namespace VehicleRentalSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_roles_creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_roles_creation));
        
        string IMigrationMetadata.Id
        {
            get { return "202310141822576_user_roles_creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
